global:
  appName: myApp
  environment: prod-d1
  defaultSecretEnabled: false

postgresql:
  enable: true

  imageName: ghcr.io/cloudnative-pg/postgresql:18.6@sha256:a66f9e4c34950b78668fa4741bf55e6a58227cc31a6e60c128f2ce1d4c072928

  instances: 2

  databaseName: ""
  ownerName: ""

  postInitSQL: []

  storageSize: 450Mi
  walStorageSize: 1Gi
  
  backupSchedule: "0 0 * * *"

ingresses: []
#   - nameSuffix: ""
#     serviceName: ""
#     portName: ""

services: []
# - nameSuffix: ""
#   portName: ""
#   port: 5302
