apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.global.appName }}-postgresql-server-certificate
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.global.appName }}
    app.kubernetes.io/component: database-certificate
    app.kubernetes.io/instance: {{ .Values.global.appName }}-{{ .Values.global.environment }}
    app.kubernetes.io/managed-by: argocd
spec:
  secretName: {{ .Values.global.appName }}-postgresql-server-certificate-secret
  usages:
    - server auth
  issuerRef:
    name: vault-cnpg-kube-prod-d1-issuer
    kind: ClusterIssuer
  commonName: {{ .Values.global.appName }}-postgresql-server-certificate
  dnsNames:
    - {{ .Values.global.appName }}-postgresql-cluster-rw
    - {{ .Values.global.appName }}-postgresql-cluster-rw.{{ .Release.Namespace }}
    - {{ .Values.global.appName }}-postgresql-cluster-rw.{{ .Release.Namespace }}.svc
    - {{ .Values.global.appName }}-postgresql-cluster-r
    - {{ .Values.global.appName }}-postgresql-cluster-r.{{ .Release.Namespace }}
    - {{ .Values.global.appName }}-postgresql-cluster-r.{{ .Release.Namespace }}.svc
    - {{ .Values.global.appName }}-postgresql-cluster-ro
    - {{ .Values.global.appName }}-postgresql-cluster-ro.{{ .Release.Namespace }}
    - {{ .Values.global.appName }}-postgresql-cluster-ro.{{ .Release.Namespace }}.svc