apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.appName }}-postgresql-credentials-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.global.appName }}
    app.kubernetes.io/component: database
    app.kubernetes.io/instance: {{ .Values.global.appName }}-{{ .Values.global.environment }}
    app.kubernetes.io/managed-by: argocd
  annotations:
    cnpg.io/reload: "true"
    cnpg.io/userType: "app"
type: Opaque
