apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.global.appName }}-postgresql-external-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.global.appName }}
    app.kubernetes.io/component: database-eso
    app.kubernetes.io/instance: {{ .Values.global.appName }}-{{ .Values.global.environment }}
    app.kubernetes.io/managed-by: argocd
spec:
  refreshInterval: "24h0m0s"
  target:
    name: {{ .Values.global.appName }}-postgresql-credentials-secret
    creationPolicy: Owner
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: {{ default (printf "%suser" .Values.global.appName) (.Values.postgres.ownerName | trim) }}
        password: "{{`{{ .password }}`}}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ClusterGenerator
          name: eso-cnpg-password-generator