apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: {{ .Values.global.appName }}-postgresql-external-push-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.global.appName }}
    app.kubernetes.io/component: database-eso
    app.kubernetes.io/instance: {{ .Values.global.appName }}-{{ .Values.global.environment }}
    app.kubernetes.io/managed-by: argocd
spec:
  refreshInterval: 1h
  updatePolicy: Replace       
  deletionPolicy: None
  secretStoreRefs:
    - name: eso-vault-store
      kind: ClusterSecretStore
  selector:
    secret:
      name: {{ .Values.global.appName }}-postgresql-credentials-secret   # target secret name
  data:
    - match:
        secretKey: username
        remoteRef:
          remoteKey: {{ .Values.global.appName }}/prod-d1/postgresql     # path relative to mount 'kube-prod-d1'
          property: username                        # field inside the KV JSON document
    - match:
        secretKey: password
        remoteRef:
          remoteKey: {{ .Values.global.appName }}/prod-d1/postgresql     # path relative to mount 'kube-prod-d1'
          property: password                        # field inside the KV JSON document
